# Generated by Django 4.2 on 2023-05-07 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mikro', '0007_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
