# Generated by Django 4.2 on 2023-05-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikro', '0014_alter_router_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
