# Generated by Django 4.2 on 2023-05-07 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mikro', '0019_alter_router_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='router',
            name='user',
        ),
    ]
