# Generated by Django 4.2 on 2023-05-07 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mikro', '0021_user_router_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
