# Generated by Django 4.2 on 2023-05-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikro', '0022_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='message',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
